---
application:
  name: "m4u"
  project: "music bot"
  organization: "QoveryCommunity"
  cpu: "8"
  ram: "32GB"
  storage:
  - name: "m4u"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/"
routers:
- name: "main-m4u"
  routes:
  - application_name: "m4u"
    paths:
    - "/*"
