---
application:
  name: "m4u"
  project: "music bot"
  organization: "QoveryCommunity"
  cpu: "16"
  ram: "64GB"
  storage:
  - name: "m4u"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/d"
routers:
- name: "main-m4u"
  routes:
  - application_name: "m4u"
    paths:
    - "/*"
